### ISSUE TITLE
Detours.lib is broken

### ISSUE THREAD

**Issue by LooksEpic** [luisfelipe18/GamesoftACS#1]
That lib is not working. Project is not compiled.

**Comment by luisfelipe18** [comment]
@LooksEpic I have tested on a fresh install of Rider and clone of repository, may you try using Rider instead of visual studio? are you compiling on x32?

**Comment by LooksEpic** [comment]
Yes, I have using VS 2019 and i build Release x86

**Comment by LooksEpic** [comment]
I have downloading Rider. I try again :)
